# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5d2e22f76fa59540d468b22615a718bbebbd1ef863f8a7c685a9e615335f83c56ae7fbf02d757e6a0a6c8cedf20c7a658d13a2b0ee47ca30364986e2c8cd26f

test:
  secret_key_base: 9e2b6159927dac894aca2056639542184fb77efdb79c2fc9efe8cb3be710c8e0cd84abf1b08ed56c2e80ec8fabc6f5d4cbd8de6af74307808c65e0fdeece6e9d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
